import { IGallowsType, languages } from '../types/types'
import { GALLOWSTHEMESEng } from './GallowsThemesEng'
import { GALLOWSTHEMESPL } from './GallowsThemesPl'
import { GALLOWSTHEMESRU } from './GallowsThemesRu'
import { GALLOWSTHEMESUa } from './GallowsThemesUa'

export const LANGUAGES: { value: languages; label: string }[] = [
	{ value: 'ru', label: '/games-collection/Flag_of_Russia.svg' },
	{ value: 'en', label: '/games-collection/usa.svg' },
	{ value: 'pl', label: '/games-collection/pl.svg' },
	{ value: 'ua', label: '/games-collection/ua.svg' },
]

export const LETTERS = {
	ru: [
		'а',
		'б',
		'в',
		'г',
		'д',
		'е',
		'ё',
		'ж',
		'з',
		'и',
		'й',
		'к',
		'л',
		'м',
		'н',
		'о',
		'п',
		'р',
		'с',
		'т',
		'у',
		'ф',
		'х',
		'ц',
		'ч',
		'ш',
		'щ',
		'ы',
		'ь',
		'э',
		'ю',
		'я',
	],
	en: [
		'a',
		'b',
		'c',
		'd',
		'e',
		'f',
		'g',
		'h',
		'i',
		'j',
		'k',
		'l',
		'm',
		'n',
		'o',
		'p',
		'q',
		'r',
		's',
		't',
		'u',
		'v',
		'w',
		'x',
		'y',
		'z',
	],
	pl: [
		'a',
		'ą',
		'b',
		'c',
		'ć',
		'd',
		'e',
		'ę',
		'f',
		'g',
		'h',
		'i',
		'j',
		'k',
		'l',
		'ł',
		'm',
		'n',
		'ń',
		'o',
		'ó',
		'p',
		'q',
		'r',
		's',
		'ś',
		't',
		'u',
		'v',
		'w',
		'x',
		'y',
		'z',
		'ż',
		'ź',
	],
	ua: [
		'а',
		'б',
		'в',
		'г',
		'д',
		'е',
		'є',
		'ж',
		'з',
		'и',
		'і',
		'ї',
		'й',
		'к',
		'л',
		'м',
		'н',
		'о',
		'п',
		'р',
		'с',
		'т',
		'у',
		'ф',
		'х',
		'ц',
		'ч',
		'ш',
		'щ',
		'ь',
		'ю',
		'я',
	],
}

const themesRU: IGallowsType[] = [
	{ type: 'random', value: 'Случайная', words: GALLOWSTHEMESRU[0].words },
	{ type: 'animals', value: 'Животные', words: GALLOWSTHEMESRU[1].words },
	{ type: 'landscapes', value: 'Природа', words: GALLOWSTHEMESRU[2].words },
	{ type: 'food', value: 'Еда', words: GALLOWSTHEMESRU[3].words },
	{ type: 'cities', value: 'Города', words: GALLOWSTHEMESRU[4].words },
	{ type: 'countries', value: 'Страны', words: GALLOWSTHEMESRU[5].words },
]

const themesEN: IGallowsType[] = [
	{ type: 'random', value: 'Random', words: GALLOWSTHEMESEng[0].words },
	{ type: 'animals', value: 'Animals', words: GALLOWSTHEMESEng[1].words },
	{ type: 'landscapes', value: 'Nature', words: GALLOWSTHEMESEng[2].words },
	{ type: 'food', value: 'Food', words: GALLOWSTHEMESEng[3].words },
	{ type: 'cities', value: 'Cities', words: GALLOWSTHEMESEng[4].words },
	{ type: 'countries', value: 'Countries', words: GALLOWSTHEMESEng[5].words },
]

const themesPL: IGallowsType[] = [
	{ type: 'random', value: 'Losowo', words: GALLOWSTHEMESPL[0].words },
	{ type: 'animals', value: 'Zwierzęta', words: GALLOWSTHEMESPL[1].words },
	{ type: 'landscapes', value: 'Natura', words: GALLOWSTHEMESPL[2].words },
	{ type: 'food', value: 'Jedzenie', words: GALLOWSTHEMESPL[3].words },
	{ type: 'cities', value: 'Miasta', words: GALLOWSTHEMESPL[4].words },
	{ type: 'countries', value: 'Kraje', words: GALLOWSTHEMESPL[5].words },
]

const themesUA: IGallowsType[] = [
	{ type: 'random', value: 'Випадкове', words: GALLOWSTHEMESUa[0].words },
	{ type: 'animals', value: 'Тварини', words: GALLOWSTHEMESUa[1].words },
	{ type: 'landscapes', value: 'Природа', words: GALLOWSTHEMESUa[2].words },
	{ type: 'food', value: 'Харчування', words: GALLOWSTHEMESUa[3].words },
	{ type: 'cities', value: 'Міста', words: GALLOWSTHEMESUa[4].words },
	{ type: 'countries', value: 'Країни', words: GALLOWSTHEMESUa[5].words },
]

export const LANGUAGES_DICTIONARY = {
	ru: [
		{
			theme: 'Темы',
			home: 'Домой',
			menu: 'Меню',
			answers: 'Угадано слов:',
			settings: 'Настройки',
			play: 'Играть',
			rules: 'Правила',
			wordleRules: [
				'Вам нужно угадать загаданное слово за 6 попыток, а цвет букв будет меняться, показывая, насколько вы близки к разгадке.',
				'Чтобы начать игру, просто введите любое слово, например:',
				'определенно не входит в целевое слово.',
				'есть в слове, но не в том месте',
				'есть в слове и в точном месте',
				'Еще одна попытка найти совпадающие буквы в целевом слове.',
				'И еще одна попытка...',
				'Поздравляю 🏆',
				'(кликабельно)',
			],
			letters_count: 'Количество букв:',
			language: 'Язык',
			winsIn: 'Побед в: ',
			themes: themesRU,
		},
	],
	en: [
		{
			theme: 'Themes',
			home: 'Home',
			menu: 'Menu',
			play: 'Play',
			winsIn: 'Wins in: ',
			wordleRules: [
				'You need to guess the hidden word in 6 tries, and the color of the letters will change to show how close you are to the solution.',
				'To start the game, just enter any word, for example:',
				'definitely not in the target word.',
				'are in the word, but in the wrong place',
				'is in the word and in the exact place',
				'Another try to find matching letters in the target word.',
				'And another try...',
				'Congratulations 🏆',
				'(clickable)',
			],

			answers: 'Guessed words:',
			settings: 'Settings',
			rules: 'Rules',
			letters_count: 'Letters count:',
			language: 'Language',
			themes: themesEN,
		},
	],
	pl: [
		{
			theme: 'Tematy',
			home: 'Strona główna',
			menu: 'Menu',
			play: 'Gra',
			winsIn: 'Wygranych w: ',
			wordleRules: [
				'Musisz odgadnąć słowo za 6 prób, a kolor liter będzie się zmieniać, pokazując, jak blisko jesteś do rozwiązania.',
				'Aby rozpocząć grę, po prostu wpisz dowolne słowo, na przykład:',
				'zdecydowanie nie znajduje się w docelowym słowie.',
				'są w słowie, ale na niewłaściwym miejscu',
				'jest w słowie i na właściwym miejscu',
				'Kolejna próba znalezienia pasujących liter w docelowym słowie.',
				'I jeszcze jedna próba...',
				'Gratulacje 🏆',
				'(klikalne)',
			],

			language: 'Jezyk',
			answers: 'Ugadane słowa:',
			settings: 'Ustawienia',
			rules: 'Zasady',
			letters_count: 'Ilosc liter:',
			themes: themesPL,
		},
	],
	ua: [
		{
			theme: 'Теми',
			home: 'Дім',
			menu: 'Меню',
			play: 'Грати',
			wordleRules: [
				'Вам потрібно вгадати загаданe слово за 6 спроб, а колір букв буде змінюватися, показуючи, наскільки ви близькі до розгадки.',
				'Щоб розпочати гру, просто введіть будь-яке слово, наприклад:',
				'однозначно не входить у цільове слово.',
				'є в слові, але не на своєму місці',
				'є в слові і знаходиться на правильному місці',
				'Ще одна спроба знайти співпадаючі літери в цільовому слові.',
				'І ще одна спроба...',
				'Вітаю 🏆',
				'(клікабельно)',
			],

			language: 'Мова',
			answers: 'Згадано слів:',
			rules: 'Правила',
			winsIn: 'Побед в: ',
			letters_count: 'Кількість літер:',
			settings: 'Налаштування',
			themes: themesUA,
		},
	],
}
